//LOCAL
###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/6782a5b0c997c3e0216b9baf

### Create User
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": " jDoe@test.com",
    "favoriteColor": "blue",
    "birthday": "01/09/2021"
}

### Update User
PUT  http://localhost:3000/users/6789d6e89bafae23294bd002
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": " jDoe@test.com",
    "favoriteColor": "black",
    "birthday": "12/12/2020"
}

#### Delete User
DELETE http://localhost:3000/users/6789d6e89bafae23294bd002